# GitHub Actions workflow for building and deploying to GitHub Pages
name: Deploy to GitHub Pages

on:
<<<<<<< HEAD
  # Runs on pushes targeting the 'master' branch (sesuai push terakhir Anda)
  push:
    branches: ["master"] # Ganti ke "main" jika Anda beralih ke branch 'main'
=======
  # Runs on pushes targeting the default branch (usually main or master)
  push:
    branches: ["main"] # Ganti dengan nama branch utama Anda jika bukan 'main'
>>>>>>> 49d16cb8002a6cbf9cba6fdb88fe9e9df30b2805

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: '18' # Sesuai dengan package.json Anda
=======
          node-version: '18' # Atau versi Node.js yang sesuai dengan proyek Anda
>>>>>>> 49d16cb8002a6cbf9cba6fdb88fe9e9df30b2805
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Pastikan VITE_BASE_URL (jika Anda menggunakannya di vite.config.js untuk base)
<<<<<<< HEAD
          # diatur dengan benar di sini atau langsung di vite.config.js.
          # Dalam kasus kita, base sudah diatur di vite.config.ts
=======
          # diatur dengan benar di sini atau langsung di vite.config.js
>>>>>>> 49d16cb8002a6cbf9cba6fdb88fe9e9df30b2805

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> 49d16cb8002a6cbf9cba6fdb88fe9e9df30b2805
